# Generated by Django 5.2.1 on 2025-06-20 22:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_en_us', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_pt', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Area',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('ref', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='Reference')),
                ('id', models.CharField(max_length=2, verbose_name='Id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_en_us', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_pt', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='core.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Subarea',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('ref', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, verbose_name='IEV Reference')),
                ('id', models.CharField(max_length=2, verbose_name='Id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_en_us', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_pt', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('description_en_us', models.TextField(null=True, verbose_name='Description')),
                ('description_pt', models.TextField(null=True, verbose_name='Description')),
                ('description_pt_br', models.TextField(null=True, verbose_name='Description')),
                ('description_es', models.TextField(null=True, verbose_name='Description')),
                ('source', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('source_en_us', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('source_pt', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('source_pt_br', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('source_es', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Image')),
                ('extra', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('extra_en_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('extra_pt', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('extra_pt_br', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('extra_es', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='core.subarea', verbose_name='Subarea')),
            ],
            options={
                'verbose_name': 'Term',
            },
        ),
    ]
