# Generated by Django 5.2.1 on 2025-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='extra_en_us',
            new_name='extra_en',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='source_en_us',
            new_name='source_en',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='term',
            name='name_en_us',
        ),
        migrations.AddField(
            model_name='area',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='term',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
    ]
