# Generated by Django 5.2.1 on 2025-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_description_en_us_term_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
    ]
