# Generated by Django 5.2.1 on 2025-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_area_name_alter_area_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarea',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('ref', 'name'), name='unique_subarea_area'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('ref', 'name_en'), name='unique_subarea_area-name_en'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('ref', 'name_pt'), name='unique_subarea_area-name_pt'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('ref', 'name_pt_br'), name='unique_subarea_area-name_pt_br'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('ref', 'name_es'), name='unique_subarea_area-name_es'),
        ),
    ]
