# Generated by Django 5.2.1 on 2025-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subarea_name_alter_subarea_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subarea',
            name='unique_subarea_area',
        ),
        migrations.RemoveConstraint(
            model_name='subarea',
            name='unique_subarea_area-name_en',
        ),
        migrations.RemoveConstraint(
            model_name='subarea',
            name='unique_subarea_area-name_pt',
        ),
        migrations.RemoveConstraint(
            model_name='subarea',
            name='unique_subarea_area-name_pt_br',
        ),
        migrations.RemoveConstraint(
            model_name='subarea',
            name='unique_subarea_area-name_es',
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
