# Generated by Django 5.2.1 on 2025-07-22 22:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subarea_unique_subarea_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', ckeditor.fields.RichTextField(verbose_name='Mensagem')),
                ('ativo', models.BooleanField(default=False, verbose_name='Exibir na página inicial')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
