# Generated by Django 5.2.1 on 2025-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ocultar após'),
        ),
        migrations.AddField(
            model_name='news',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exibir a partir de'),
        ),
        migrations.AddField(
            model_name='news',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativa'),
        ),
    ]
