# Generated by Django 5.2.1 on 2025-07-27 18:51

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news_fim_news_inicio_news_titulo_alter_news_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='news',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='news',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='news',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='news',
            name='titulo',
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hide after'),
        ),
        migrations.AddField(
            model_name='news',
            name='message',
            field=ckeditor.fields.RichTextField(default='sem mensagem', verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Show from'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Untitled', max_length=200, verbose_name='Title'),
        ),
    ]
