# Generated by Django 5.2.1 on 2025-08-01 09:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_options_remove_news_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='term',
            name='extra',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='extra_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='extra_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='extra_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='extra_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
