# Generated by Django 5.2.1 on 2025-08-01 17:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Untitled', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
