# Generated by Django 5.2.1 on 2025-08-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tutorial_options_tutorial_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['position'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
