# Generated by Django 5.2.1 on 2025-08-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tutorial_options_tutorial_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
