# Generated by Django 5.2.1 on 2025-08-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactinfo_documentationlink_poster_thesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['position'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
