# Generated by Django 5.2.1 on 2025-08-05 19:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_warning_alter_news_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Warning', 'verbose_name_plural': 'Warnings'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='message',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='one-off-content-linhacomandos', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='Untitled', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(default='Untitled', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt',
            field=models.CharField(default='Untitled', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt_br',
            field=models.CharField(default='Untitled', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='warning',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='warning',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='warning',
            name='content_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='warning',
            name='content_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='warning',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='warning',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='warning',
            name='title_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='warning',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='hide_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hide after'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='show_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Show from'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
