# Generated by Django 5.2.1 on 2025-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_news_title_alter_news_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_message', models.TextField(blank=True, help_text='Mensagem exibida no topo da página de contactos.')),
                ('top_message_en', models.TextField(blank=True, help_text='Mensagem exibida no topo da página de contactos.', null=True)),
                ('top_message_pt', models.TextField(blank=True, help_text='Mensagem exibida no topo da página de contactos.', null=True)),
                ('top_message_pt_br', models.TextField(blank=True, help_text='Mensagem exibida no topo da página de contactos.', null=True)),
                ('top_message_es', models.TextField(blank=True, help_text='Mensagem exibida no topo da página de contactos.', null=True)),
            ],
            options={
                'verbose_name': 'Contact page settings',
                'verbose_name_plural': 'Contact page settings',
            },
        ),
    ]
