# Generated by Django 5.2.1 on 2025-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contactpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTopMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message')),
                ('text_en', models.TextField(null=True, verbose_name='Message')),
                ('text_pt', models.TextField(null=True, verbose_name='Message')),
                ('text_pt_br', models.TextField(null=True, verbose_name='Message')),
                ('text_es', models.TextField(null=True, verbose_name='Message')),
                ('active', models.BooleanField(default=True)),
                ('show_from', models.DateTimeField(blank=True, null=True)),
                ('hide_after', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', '-id'),
            },
        ),
        migrations.DeleteModel(
            name='ContactPageSettings',
        ),
    ]
