# Generated by Django 5.2.1 on 2025-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_news_options_news_position_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warning',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Warning', 'verbose_name_plural': 'Warnings'},
        ),
        migrations.AddField(
            model_name='warning',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
