# Generated by Django 5.2.1 on 2025-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_warning_options_warning_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Poster', 'verbose_name_plural': 'Posters'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='poster',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
