# Generated by Django 5.2.1 on 2025-08-12 12:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_poster_options_contactinfo_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='url_en',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='url_es',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='url_pt',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='url_pt_br',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='poster',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poster',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poster',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poster',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url_es',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url_pt',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url_pt_br',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
