# Generated by Django 5.2.1 on 2025-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_poster_uploaded_at_contactinfo_details_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='file_en',
            field=models.FileField(null=True, upload_to='poster/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='poster',
            name='file_es',
            field=models.FileField(null=True, upload_to='poster/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='poster',
            name='file_pt',
            field=models.FileField(null=True, upload_to='poster/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='poster',
            name='file_pt_br',
            field=models.FileField(null=True, upload_to='poster/', verbose_name='PDF File'),
        ),
    ]
