# Generated by Django 5.2.1 on 2025-08-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_poster_file_en_poster_file_es_poster_file_pt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='file_es',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='file_pt',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='file_pt_br',
        ),
    ]
