# Generated by Django 5.2.1 on 2025-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_poster_file_en_poster_file_es_poster_file_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationlink',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
