# Generated by Django 5.2.1 on 2025-08-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_documentationlink_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='name_pt_br',
        ),
    ]
