# Generated by Django 5.2.1 on 2025-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_contactinfo_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
