# Generated by Django 5.2.1 on 2025-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_tutorial_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
