# Generated by Django 5.2.1 on 2025-08-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_poster_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='uploaded_at',
        ),
    ]
