# Generated by Django 5.2.1 on 2025-08-12 21:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_thesis_uploaded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationlink',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'ordering': ['position'], 'verbose_name': 'Poster', 'verbose_name_plural': 'Posters'},
        ),
        migrations.AlterField(
            model_name='warning',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='content_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='content_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
    ]
