# Generated by Django 5.2.1 on 2025-08-13 14:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_documentationlink_options_alter_poster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
    ]
