# Generated by Django 5.2.1 on 2025-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_term_description_alter_term_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='published_at_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='published_at_es',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='published_at_pt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='published_at_pt_br',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_i18n',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last IEVP update'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_i18n_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last IEVP update'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_i18n_es',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last IEVP update'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_i18n_pt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last IEVP update'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_i18n_pt_br',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last IEVP update'),
        ),
    ]
