# Generated by Django 5.2.1 on 2025-08-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_term_published_at_term_published_at_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='updated_i18n',
        ),
        migrations.RemoveField(
            model_name='term',
            name='updated_i18n_en',
        ),
        migrations.RemoveField(
            model_name='term',
            name='updated_i18n_es',
        ),
        migrations.RemoveField(
            model_name='term',
            name='updated_i18n_pt',
        ),
        migrations.RemoveField(
            model_name='term',
            name='updated_i18n_pt_br',
        ),
    ]
