# Generated by Django 5.2.1 on 2025-08-13 23:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_term_updated_i18n_remove_term_updated_i18n_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contacttopmessage',
            name='text_fr',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='url_fr',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='poster',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poster',
            name='file_fr',
            field=models.FileField(null=True, upload_to='poster/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='term',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='term',
            name='extra_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='term',
            name='published_at_fr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='source_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url_fr',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='warning',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='warning',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
