# Generated by Django 5.2.1 on 2025-09-07 21:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_area_name_ar_area_name_bg_area_name_bs_area_name_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name_pt_pt',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='details_pt_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contacttopmessage',
            name='text_pt_pt',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='name_pt_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Link Name'),
        ),
        migrations.AddField(
            model_name='documentationlink',
            name='url_pt_pt',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='poster',
            name='description_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poster',
            name='file_pt_pt',
            field=models.FileField(null=True, upload_to='poster/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='poster',
            name='title_pt_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='name_pt_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='term',
            name='description_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='term',
            name='extra_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_pt_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='term',
            name='published_at_pt_pt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added to IEVP'),
        ),
        migrations.AddField(
            model_name='term',
            name='source_pt_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='description_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_pt_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_pt_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url_pt_pt',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='warning',
            name='content_pt_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='warning',
            name='title_pt_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
