# Generated by Django 5.2.1 on 2025-09-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_area_name_pt_pt_contactinfo_details_pt_pt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='name_pt_pt',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='details_pt_pt',
        ),
        migrations.RemoveField(
            model_name='contacttopmessage',
            name='text_pt_pt',
        ),
        migrations.RemoveField(
            model_name='documentationlink',
            name='name_pt_pt',
        ),
        migrations.RemoveField(
            model_name='documentationlink',
            name='url_pt_pt',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_pt_pt',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_pt_pt',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='description_pt_pt',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='file_pt_pt',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='title_pt_pt',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='name_pt_pt',
        ),
        migrations.RemoveField(
            model_name='term',
            name='description_pt_pt',
        ),
        migrations.RemoveField(
            model_name='term',
            name='extra_pt_pt',
        ),
        migrations.RemoveField(
            model_name='term',
            name='name_pt_pt',
        ),
        migrations.RemoveField(
            model_name='term',
            name='published_at_pt_pt',
        ),
        migrations.RemoveField(
            model_name='term',
            name='source_pt_pt',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='description_pt_pt',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='title_pt_pt',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='content_pt_pt',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='title_pt_pt',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='video_url_pt_pt',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='content_pt_pt',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='title_pt_pt',
        ),
    ]
